#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LGA")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LGAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CounterConection> CounterConections
		{
			get
			{
				return this.GetTable<CounterConection>();
			}
		}
		
		public System.Data.Linq.Table<CounterRefill> CounterRefills
		{
			get
			{
				return this.GetTable<CounterRefill>();
			}
		}
		
		public System.Data.Linq.Table<DeliveryManData> DeliveryManDatas
		{
			get
			{
				return this.GetTable<DeliveryManData>();
			}
		}
		
		public System.Data.Linq.Table<DellyData> DellyDatas
		{
			get
			{
				return this.GetTable<DellyData>();
			}
		}
		
		public System.Data.Linq.Table<IncomingStock> IncomingStocks
		{
			get
			{
				return this.GetTable<IncomingStock>();
			}
		}
		
		public System.Data.Linq.Table<Stock> Stocks
		{
			get
			{
				return this.GetTable<Stock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CounterConection")]
	public partial class CounterConection
	{
		
		private int _Id;
		
		private string _ConnectionType;
		
		private string _Name;
		
		private string _Address;
		
		private string _CylGiven;
		
		private System.Nullable<int> _Filled;
		
		private System.Nullable<int> _Empty;
		
		private System.Nullable<int> _Regulator;
		
		private System.Nullable<int> _Trolly;
		
		private System.Nullable<int> _Stove;
		
		private System.Nullable<int> _RuberTube;
		
		private System.Nullable<int> _Amount;
		
		private System.Nullable<int> _DayEndTotal;
		
		private System.Nullable<System.DateTime> _Date;
		
		public CounterConection()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionType", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ConnectionType
		{
			get
			{
				return this._ConnectionType;
			}
			set
			{
				if ((this._ConnectionType != value))
				{
					this._ConnectionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CylGiven", DbType="VarChar(MAX)")]
		public string CylGiven
		{
			get
			{
				return this._CylGiven;
			}
			set
			{
				if ((this._CylGiven != value))
				{
					this._CylGiven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Int")]
		public System.Nullable<int> Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empty", DbType="Int")]
		public System.Nullable<int> Empty
		{
			get
			{
				return this._Empty;
			}
			set
			{
				if ((this._Empty != value))
				{
					this._Empty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regulator", DbType="Int")]
		public System.Nullable<int> Regulator
		{
			get
			{
				return this._Regulator;
			}
			set
			{
				if ((this._Regulator != value))
				{
					this._Regulator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trolly", DbType="Int")]
		public System.Nullable<int> Trolly
		{
			get
			{
				return this._Trolly;
			}
			set
			{
				if ((this._Trolly != value))
				{
					this._Trolly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stove", DbType="Int")]
		public System.Nullable<int> Stove
		{
			get
			{
				return this._Stove;
			}
			set
			{
				if ((this._Stove != value))
				{
					this._Stove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RuberTube", DbType="Int")]
		public System.Nullable<int> RuberTube
		{
			get
			{
				return this._RuberTube;
			}
			set
			{
				if ((this._RuberTube != value))
				{
					this._RuberTube = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayEndTotal", DbType="Int")]
		public System.Nullable<int> DayEndTotal
		{
			get
			{
				return this._DayEndTotal;
			}
			set
			{
				if ((this._DayEndTotal != value))
				{
					this._DayEndTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CounterRefill")]
	public partial class CounterRefill
	{
		
		private int _Id;
		
		private string _CylType;
		
		private System.Nullable<int> _ConsumerNo;
		
		private string _Name;
		
		private System.Nullable<int> _Filled;
		
		private System.Nullable<int> _Empty;
		
		private System.Nullable<int> _Amount;
		
		private System.Nullable<double> _DayEndTotal;
		
		private System.Nullable<System.DateTime> _Daate;
		
		public CounterRefill()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CylType", DbType="VarChar(MAX)")]
		public string CylType
		{
			get
			{
				return this._CylType;
			}
			set
			{
				if ((this._CylType != value))
				{
					this._CylType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumerNo", DbType="Int")]
		public System.Nullable<int> ConsumerNo
		{
			get
			{
				return this._ConsumerNo;
			}
			set
			{
				if ((this._ConsumerNo != value))
				{
					this._ConsumerNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Int")]
		public System.Nullable<int> Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empty", DbType="Int")]
		public System.Nullable<int> Empty
		{
			get
			{
				return this._Empty;
			}
			set
			{
				if ((this._Empty != value))
				{
					this._Empty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayEndTotal", DbType="Float")]
		public System.Nullable<double> DayEndTotal
		{
			get
			{
				return this._DayEndTotal;
			}
			set
			{
				if ((this._DayEndTotal != value))
				{
					this._DayEndTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Daate
		{
			get
			{
				return this._Daate;
			}
			set
			{
				if ((this._Daate != value))
				{
					this._Daate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeliveryManData")]
	public partial class DeliveryManData
	{
		
		private int _Id;
		
		private string _DeliveryManName;
		
		private string _Area;
		
		private System.Nullable<int> _Cost;
		
		private int _Filled;
		
		private int _Empty;
		
		private int _Amount;
		
		private int _Online;
		
		private int _DayEndTotal;
		
		private System.DateTime _Date;
		
		public DeliveryManData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryManName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DeliveryManName
		{
			get
			{
				return this._DeliveryManName;
			}
			set
			{
				if ((this._DeliveryManName != value))
				{
					this._DeliveryManName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(MAX)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int")]
		public System.Nullable<int> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Int NOT NULL")]
		public int Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empty", DbType="Int NOT NULL")]
		public int Empty
		{
			get
			{
				return this._Empty;
			}
			set
			{
				if ((this._Empty != value))
				{
					this._Empty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int NOT NULL")]
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Online", DbType="Int NOT NULL")]
		public int Online
		{
			get
			{
				return this._Online;
			}
			set
			{
				if ((this._Online != value))
				{
					this._Online = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayEndTotal", DbType="Int NOT NULL")]
		public int DayEndTotal
		{
			get
			{
				return this._DayEndTotal;
			}
			set
			{
				if ((this._DayEndTotal != value))
				{
					this._DayEndTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DellyData")]
	public partial class DellyData
	{
		
		private int _Id;
		
		private string _Source;
		
		private int _Filled;
		
		private int _Empty;
		
		private int _Pending;
		
		private System.DateTime _Date;
		
		public DellyData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this._Source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Int NOT NULL")]
		public int Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empty", DbType="Int NOT NULL")]
		public int Empty
		{
			get
			{
				return this._Empty;
			}
			set
			{
				if ((this._Empty != value))
				{
					this._Empty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pending", DbType="Int NOT NULL")]
		public int Pending
		{
			get
			{
				return this._Pending;
			}
			set
			{
				if ((this._Pending != value))
				{
					this._Pending = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IncomingStock")]
	public partial class IncomingStock
	{
		
		private int _Id;
		
		private string _Source;
		
		private int _Filled;
		
		private int _Empty;
		
		private System.DateTime _Date;
		
		public IncomingStock()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this._Source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Int NOT NULL")]
		public int Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empty", DbType="Int NOT NULL")]
		public int Empty
		{
			get
			{
				return this._Empty;
			}
			set
			{
				if ((this._Empty != value))
				{
					this._Empty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stock")]
	public partial class Stock
	{
		
		private int _Id;
		
		private System.Nullable<int> @__14_2_cyl;
		
		private System.Nullable<int> @__19_cyl;
		
		private System.Nullable<int> @__5_19_cyl;
		
		private System.Nullable<int> _Regulator;
		
		private System.Nullable<int> _Trolly;
		
		private System.Nullable<int> _Stove;
		
		private System.Nullable<int> _RuberTube;
		
		public Stock()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[14.2 cyl]", Storage="__14_2_cyl", DbType="Int")]
		public System.Nullable<int> _14_2_cyl
		{
			get
			{
				return this.@__14_2_cyl;
			}
			set
			{
				if ((this.@__14_2_cyl != value))
				{
					this.@__14_2_cyl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[19 cyl]", Storage="__19_cyl", DbType="Int")]
		public System.Nullable<int> _19_cyl
		{
			get
			{
				return this.@__19_cyl;
			}
			set
			{
				if ((this.@__19_cyl != value))
				{
					this.@__19_cyl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5.19 cyl]", Storage="__5_19_cyl", DbType="Int")]
		public System.Nullable<int> _5_19_cyl
		{
			get
			{
				return this.@__5_19_cyl;
			}
			set
			{
				if ((this.@__5_19_cyl != value))
				{
					this.@__5_19_cyl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regulator", DbType="Int")]
		public System.Nullable<int> Regulator
		{
			get
			{
				return this._Regulator;
			}
			set
			{
				if ((this._Regulator != value))
				{
					this._Regulator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trolly", DbType="Int")]
		public System.Nullable<int> Trolly
		{
			get
			{
				return this._Trolly;
			}
			set
			{
				if ((this._Trolly != value))
				{
					this._Trolly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stove", DbType="Int")]
		public System.Nullable<int> Stove
		{
			get
			{
				return this._Stove;
			}
			set
			{
				if ((this._Stove != value))
				{
					this._Stove = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RuberTube", DbType="Int")]
		public System.Nullable<int> RuberTube
		{
			get
			{
				return this._RuberTube;
			}
			set
			{
				if ((this._RuberTube != value))
				{
					this._RuberTube = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
